In [32]:
#создание различных массивов из обычного списка и из специальных функций
import numpy as np

array = np.array([1,2,3,4,5]) #создаем одномерный массив
print('array')
print(array)

array1 = np.ones((2,1,3)) #создаем массив единиц размером (2,1,3)
print('array1')
print(array1)

array2 = np.eye(5) #создаем единичную матрицу размером (5,5)
print('array2')
print(array2)

array3 = np.zeros((3,3)) #создаем матрицу с нулями  размером (3,3)
print('array3')
print(array3)

array4 = np.arange(10,50,5) #создаем массив от 10 до 50 с шагом 5
print('array4')
print(array4)

array5 = np.empty((4,2,1)) #создаем небольшую трехмерную матрицу, заполненную мусором
print('array5')
print(array5)

array6 = np.arange(1,1000,0.0001) #создаем массив с большим количеством элементов
print('array6')
print(array6)

array
[1 2 3 4 5]
array1
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
array2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
array3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array4
[10 15 20 25 30 35 40 45]
array5
[[[4.94e-323]
  [7.41e-323]]

 [[9.88e-323]
  [1.24e-322]]

 [[1.48e-322]
  [1.73e-322]]

 [[1.98e-322]
  [2.22e-322]]]
array6
[  1.       1.0001   1.0002 ... 999.9997 999.9998 999.9999]


In [35]:
#печатаем полученный массивы
print(array.shape)
print(type(array))
print(array1.shape)
print(type(array1))

(5,)
<class 'numpy.ndarray'>
(2, 1, 3)
<class 'numpy.ndarray'>


In [36]:
# задаем параметры для вывода большого массива
np.set_printoptions(threshold=100, precision=10)
print(array6)
np.set_printoptions(threshold=1000, precision=8) #затем возвращаем стандартные настройки

[  1.             1.0001         1.0002       ... 999.9996999999
 999.9997999999 999.9998999999]


In [48]:
#Базовые операции с массивами
a = np.array([4,5,6,7,8]) #первый массив
print(a)
b = np.eye(2) #второй массив
print(b)

#сложим их и получим ошибку, так как размеры не совпадают
#print(a+b)

c = np.arange(5)
print(c)

print(a+c) #сложение

[4 5 6 7 8]
[[1. 0.]
 [0. 1.]]
[0 1 2 3 4]
[ 4  6  8 10 12]


In [44]:
print(a-c) #вычитание

[4 4 4 4 4]


In [45]:
print(a*c) #поэлементное умножение

[ 0  5 12 21 32]


In [49]:
print(a/c) #поэлементное деление
#вернет ошибку с делением на 0, но программа вернула массив результата с элементом inf

[       inf 5.         3.         2.33333333 2.        ]


C:\Users\EcoRestart\AppData\Local\Temp\ipykernel_19548\2746041099.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a/c) #поэлементное деление


In [51]:
arr = np.arange(1,30,2)*3 #поэлементное умножение на скаляр
arr

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87])

In [55]:
arr[3] #получаем элемент

np.int64(21)

In [61]:
arr[2:5] #получаем срез

array([3, 3, 3])

In [60]:
arr[[3,4]] #получаем массив с конкретными элементами

array([3, 3])

In [59]:
arr[2:5] = 3 #поменяли
arr

array([ 3,  9,  3,  3,  3, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87])

In [63]:
mat = np.array([[1,2,3,4],
               [11,12,13,14],
               [21,22,23,24],
               [31,32,33,34]])
mat

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [72]:
print(mat[1,2])
print(mat[1][2])
print(mat[2:3])
print(mat[2:3,2:3])
print(mat[[2,3],3])

13
13
[[21 22 23 24]]
[[23]]
[24 34]


In [73]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [74]:
a.shape

(2, 2, 3)

In [8]:
#Получение статистических показателей
import random
import numpy as np
import numpy.random as rand
array = np.random.sample(50) #массив со случайными числами 50 элементов
print(np.mean(array)) # среднее значение
print(np.median(array)) # медиана

0.49934017187349644
0.49670462460115067
