In [32]:
#создание различных массивов из обычного списка и из специальных функций
import numpy as np

array = np.array([1,2,3,4,5]) #создаем одномерный массив
print('array')
print(array)

array1 = np.ones((2,1,3)) #создаем массив единиц размером (2,1,3)
print('array1')
print(array1)

array2 = np.eye(5) #создаем единичную матрицу размером (5,5)
print('array2')
print(array2)

array3 = np.zeros((3,3)) #создаем матрицу с нулями  размером (3,3)
print('array3')
print(array3)

array4 = np.arange(10,50,5) #создаем массив от 10 до 50 с шагом 5
print('array4')
print(array4)

array5 = np.empty((4,2,1)) #создаем небольшую трехмерную матрицу, заполненную мусором
print('array5')
print(array5)

array6 = np.arange(1,1000,0.0001) #создаем массив с большим количеством элементов
print('array6')
print(array6)

array
[1 2 3 4 5]
array1
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
array2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
array3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array4
[10 15 20 25 30 35 40 45]
array5
[[[4.94e-323]
  [7.41e-323]]

 [[9.88e-323]
  [1.24e-322]]

 [[1.48e-322]
  [1.73e-322]]

 [[1.98e-322]
  [2.22e-322]]]
array6
[  1.       1.0001   1.0002 ... 999.9997 999.9998 999.9999]


In [35]:
#печатаем полученный массивы
print(array.shape)
print(type(array))
print(array1.shape)
print(type(array1))

(5,)
<class 'numpy.ndarray'>
(2, 1, 3)
<class 'numpy.ndarray'>


In [36]:
# задаем параметры для вывода большого массива
np.set_printoptions(threshold=100, precision=10)
print(array6)
np.set_printoptions(threshold=1000, precision=8) #затем возвращаем стандартные настройки

[  1.             1.0001         1.0002       ... 999.9996999999
 999.9997999999 999.9998999999]


In [48]:
#Базовые операции с массивами
a = np.array([4,5,6,7,8]) #первый массив
print(a)
b = np.eye(2) #второй массив
print(b)

#сложим их и получим ошибку, так как размеры не совпадают
#print(a+b)

c = np.arange(5)
print(c)

print(a+c) #сложение

[4 5 6 7 8]
[[1. 0.]
 [0. 1.]]
[0 1 2 3 4]
[ 4  6  8 10 12]


In [44]:
print(a-c) #вычитание

[4 4 4 4 4]


In [45]:
print(a*c) #поэлементное умножение

[ 0  5 12 21 32]


In [49]:
print(a/c) #поэлементное деление
#вернет ошибку с делением на 0, но программа вернула массив результата с элементом inf

[       inf 5.         3.         2.33333333 2.        ]


C:\Users\EcoRestart\AppData\Local\Temp\ipykernel_19548\2746041099.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a/c) #поэлементное деление


In [51]:
arr = np.arange(1,30,2)*3 #поэлементное умножение на скаляр
arr

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87])

In [55]:
arr[3] #получаем элемент

np.int64(21)

In [61]:
arr[2:5] #получаем срез

array([3, 3, 3])

In [60]:
arr[[3,4]] #получаем массив с конкретными элементами

array([3, 3])

In [59]:
arr[2:5] = 3 #поменяли
arr

array([ 3,  9,  3,  3,  3, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87])

In [63]:
mat = np.array([[1,2,3,4],
               [11,12,13,14],
               [21,22,23,24],
               [31,32,33,34]])
mat

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [72]:
print(mat[1,2])
print(mat[1][2])
print(mat[2:3])
print(mat[2:3,2:3])
print(mat[[2,3],3])

13
13
[[21 22 23 24]]
[[23]]
[24 34]


In [73]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [74]:
a.shape

(2, 2, 3)

In [4]:
#Получение статистических показателей
import random
import numpy as np
import numpy.random as rand
array = np.random.sample(50) #массив со случайными числами 50 элементов
print(np.mean(array)) # среднее значение
print(np.median(array)) # медиана

0.45792056763307015
0.38804526003054274


In [11]:
#использование двумерного массива для расчета статистических данных
array2 = np.random.sample((10,10))
print(np.mean(array2))
print(np.median(array2))
print(array2)

0.49167172768012773
0.4595027052842978
[[0.54585435 0.89101814 0.51946895 0.51906117 0.12920919 0.9038567
  0.13310997 0.64396843 0.57244685 0.33062803]
 [0.45866722 0.58330211 0.48438567 0.02242547 0.72558109 0.90587648
  0.28599543 0.14259435 0.68785428 0.93826053]
 [0.60393285 0.12528721 0.1362951  0.80315242 0.14495594 0.30721062
  0.3825126  0.72621873 0.24948495 0.04304104]
 [0.22709799 0.35137462 0.74217446 0.30990119 0.33125792 0.90283594
  0.64633408 0.66718108 0.07272433 0.29938177]
 [0.04572544 0.57467392 0.33677274 0.65299193 0.95067686 0.75463975
  0.39835681 0.81728672 0.40984937 0.39837143]
 [0.8569621  0.17579651 0.60021551 0.42592203 0.78205963 0.43128572
  0.60775036 0.4745559  0.90830816 0.80472663]
 [0.56711394 0.37489277 0.80903157 0.94111092 0.66995653 0.08240943
  0.19505206 0.44234079 0.49916307 0.78383073]
 [0.24930787 0.54789646 0.66020596 0.62246669 0.63464173 0.20971589
  0.45216047 0.31075996 0.42259479 0.85720222]
 [0.46033819 0.31500383 0.1033762  0.37489